server:
  port: 16770
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true

kafka:
  bootStrapAddress: 192.168.0.131:9092
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    maximum-pool-size: 4
    url: jdbc:postgresql://192.168.0.130:5432/DTrixData
    username: root
    password: keystone42086
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      format_sql: true
      show_sql: true
logging:
  level:
    root: info


eureka:
  instance:
    #    hostname: RL-PC
    #    ip-address: 192.168.0.135
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.49:8761/eureka/  #,http://192.168.0.141:8761/eureka/,http://192.168.0.142:8761/eureka/